Feature/button component
isdi-coders-2023/coding-adventure-Victor-Andujar-front-202301-BCN pull request #1
Opened 2023-02-27 15:31 UTC by victorandujar

2023-02-27 15:58 UTC, benjaminrae requested changes

2023-02-27 16:00 UTC, victorandujar commented on src/components/Button/Button.tsx
> +const Button = (): JSX.Element => {
esque no se a que te refieres con que recibe un texto. por pops?

2023-02-27 16:00 UTC, victorandujar commented on src/components/Button/ButtonStyled.tsx
> +const ButtonStyled = styled.button`
no lo sabía, tampoco lo pone en el enunciado.

2023-02-27 16:14 UTC, victorandujar commented on src/components/Button/ButtonStyled.tsx
> +const ButtonStyled = styled.button`
Ben, no se si lo habréis dicho en clase, pero no encuentro los estilos para cuando tenga que estar disabled. Quizás estoy ciego, que podría ser.

2023-02-27 16:46 UTC, victorandujar commented on src/components/Button/ButtonStyled.tsx
> +import "@fontsource/saira-stencil-one";
Ben, he importado la fuente en index.tsx

2023-02-27 16:46 UTC, victorandujar commented on src/components/Button/Button.tsx
> +const Button = (): JSX.Element => {
Esto también debería estar arreglado :D

2023-02-27 16:50 UTC, benjaminrae requested changes

2023-02-27 16:50 UTC, benjaminrae commented on src/components/Button/Button.test.tsx
>      test("Then it should show the button with the text 'Sign up'", () => {
El boton que renderizas en el test no tiene el texto Sign up

2023-02-27 16:50 UTC, benjaminrae commented on src/components/Button/ButtonStyled.tsx
> +const ButtonStyled = styled.button`
En Figma puedes ver todas las variantes de boton

2023-02-27 16:50 UTC, benjaminrae commented on src/components/Form/Form.tsx
> +const Form = (): JSX.Element => {
Porque hay un Form en esta rama?

2023-02-27 16:51 UTC, victorandujar commented on src/components/Form/Form.tsx
> +const Form = (): JSX.Element => {
Porque soy desgrasiau. He querido ir de guay y la he liado padre. Ahora lo borro, corrijo lo del test y vuelvo a hacer push.

2023-02-27 16:54 UTC, victorandujar commented on src/components/Form/Form.tsx
> +const Form = (): JSX.Element => {
Debería estar correjido todo ya.

2023-02-27 16:57 UTC, benjaminrae requested changes
Ahora que hay tests, hay que quitar passWithNoTests

2023-02-27 17:22 UTC, benjaminrae requested changes
Hace falta quitar --passWithNoTests

2023-02-27 17:22 UTC, benjaminrae commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Hay que quitar los colores a variables

2023-02-27 17:38 UTC, victorandujar commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Vale, hecho.

2023-02-27 17:41 UTC, MMLORENA commented
@victorandujar ya tienes test, elimina del script de test el PassWithNoTest

2023-02-28 12:03 UTC, victorandujar commented
Hola Ben, en principio está todo corregido. Cuando puedas me dices ;)

2023-02-28 14:34 UTC, bertoforteza approved these changes

2023-03-01 10:09 UTC, merged