Feature/form component
isdi-coders-2023/coding-adventure-Victor-Andujar-front-202301-BCN pull request #2
Opened 2023-02-27 15:51 UTC by victorandujar

2023-02-27 16:10 UTC, MMLORENA requested changes

2023-02-27 16:10 UTC, MMLORENA commented on src/components/Form/Form.tsx
> +const Form = (): JSX.Element => {
El naming Form es poco preciso, debería tener un nombre más específico

2023-02-27 16:10 UTC, MMLORENA commented on src/components/Button/Button.test.tsx
> +      const buttonText = "Sign up";
¿qué hace aquí en está PR este archivo?

2023-02-27 16:10 UTC, MMLORENA commented on src/components/Button/Button.tsx
> +const Button = (): JSX.Element => {
¿Por qué está este archivo?

2023-02-27 16:10 UTC, MMLORENA commented on src/components/Button/ButtonStyled.tsx
> +  height: 2.5rem;
No corresponde a esta PR

2023-02-27 16:10 UTC, MMLORENA commented on src/components/Form/Form.tsx
> +      <input type="text" className="register-form__input" />
No utilizamos el naming de las tag html en el naming de las clases

2023-02-27 16:10 UTC, MMLORENA commented on src/components/Form/Form.tsx
> +      <input type="text" className="register-form__input" />
El input del password no debería ser type text

2023-02-27 16:27 UTC, victorandujar commented on src/components/Button/Button.tsx
> +const Button = (): JSX.Element => {
porque soy tonto, me he ido a master, he mergeado la rama de Button component y entonces he abierto una nueva rama desde master para el Form. No quería volver a crear la carpeta components y me ha parecido correcto hacer esto. Pero veo que no :(

2023-02-27 16:28 UTC, victorandujar commented on src/components/Form/Form.tsx
> +      <input type="text" className="register-form__input" />
Voy.

2023-02-27 16:28 UTC, victorandujar commented on src/components/Form/Form.tsx
> +      <input type="text" className="register-form__input" />
Okay, lo cambio.

2023-02-27 16:32 UTC, MMLORENA commented on src/components/Button/Button.tsx
> +const Button = (): JSX.Element => {
No pasa nada, pero arreglalo 😋

2023-02-27 16:59 UTC, MMLORENA requested changes

2023-02-27 16:59 UTC, MMLORENA commented on src/components/FormRegister/FormRegister.tsx
> +      <input type="text" className="register__data" />
No es type text. 
La clase del bloque es poco preciso, en todo caso debería ser register-form. 
La clase del input register__data tampoco es realmente lo que debería ser, busca otro name. 
EL htmlFor de los labels no está vinculado con los inputs

2023-02-27 16:59 UTC, MMLORENA commented on src/components/Form/Form.tsx
> +const Form = (): JSX.Element => {
mejor

2023-02-27 16:59 UTC, MMLORENA commented on src/components/Button/Button.tsx
> +const Button = (): JSX.Element => {
Okey

2023-02-27 16:59 UTC, MMLORENA commented on src/components/Form/Form.tsx
> +      <input type="text" className="register-form__input" />
Ok

2023-02-27 17:14 UTC, victorandujar commented on src/components/FormRegister/FormRegister.tsx
> +      <input type="text" className="register__data" />
Lorena, corregido a priori todo lo que me has comentado. Para que esten vinculados los labels con los  inputs, he optado por hacerlo con ID que es lo que he encontrado en la documentación. No sé si es la manera correcta. Me dices :D. Gracias

2023-02-27 17:40 UTC, MMLORENA submitted a review, later dismissed

2023-02-27 17:56 UTC, victorandujar commented on src/components/FormRegister/FormRegister.tsx
> +      <button className="register__button">Sign up</button>
Tenía entendido pq así se ha dicho en clase, que el formulario tiene su propio button independientemente de si existe un componente button. Hasta ahora siempre lo hemos hecho así, y por eso le he añadido al formulario su propio button para submitear. Por otro lado, me has comentado lo de los tests. En la PR de Button component ya lo he sacado, que es allí donde tengo el únio test. El formulario aún no está testeado porque no se pide en el enunciado y tengo que dejar el --passWithNoTests en el script porque sino el workflow de testing me da error.

2023-02-27 17:58 UTC, victorandujar commented on src/components/FormRegister/FormRegister.tsx
> +        className="register-form__credentials"
Lorena, no se que naming ponerle ya. Para mi son datos que introduce el usuario, por eso he puesto data antes. Visto de otra manera podrian ser credenciales, por eso lo he cambiado a credentials. No sé que puedo poner para que este ok.

2023-02-27 18:02 UTC, victorandujar commented on src/components/FormRegister/FormRegister.tsx
> +      <input type="email" className="register-form__credentials" id="Email" />
Corregido :D

2023-02-27 18:03 UTC, victorandujar commented on src/App.tsx
> +  return <FormRegister />;
Correcto, para hacer pruebas lo he puesto y se  me ha pasado quitarlo.

2023-02-28 14:50 UTC, bertoforteza commented on src/components/FormRegister/FormRegister.tsx
> +        className="register-form__credentials"
Víctor prueba mejor con `field` o `control` en lugar de credentials. Estas clases te servirán también para controles de formulario que no tengan nada que ver con credenciales.

2023-03-01 15:06 UTC, victorandujar commented
Menuda odisea he tenido para resolver los conflictos. Sinceramente no se que ha pasado pero he hasta sudado (no se si por la fiebre o que...) para solucionarlo. Ya me decis cuando podáis.

2023-03-01 15:36 UTC, victorandujar commented on src/components/FormRegister/FormRegister.tsx
> +        className="register-form__credentials"
guay. corregit Bert

2023-03-02 10:51 UTC, catatarelli approved these changes

2023-03-02 10:52 UTC, catatarelli commented
Dale estilos al formulario (no dar estilo al input type file).

2023-03-02 10:53 UTC, victorandujar commented
@catatarelli Perfecto. Ahora me pongo con ello. Gracias :D

2023-03-02 10:53 UTC, merged